services:
  envoy:
    image: envoyproxy/envoy:v1.26-latest
    ports:
      - "8080:8080"
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
      - .:/app
    depends_on:
      - app
  app:
    build:
      context: ./app
    ports:
      - "8000:8000"
    volumes:
      - .:/app